### ISSUE TITLE
No CMake Build Distribution

### ISSUE THREAD

**Issue by yasirroni** [ami-iit/osqp-matlab-cmake-buildsystem#9]
Does the result of CMake build platform dependent?

```
cmake -DCMAKE_INSTALL_PREFIX:PATH=<install-prefix> ..
cmake --build . --config Release
cmake --install . --config Release
```

If no, is it possible to distribute the build result? This way, user will only need to download and add to path.

**Comment by traversaro** [comment]
> Does the result of CMake build platform dependent?

No, the CMake build will produce a mex file, that is basically a [shared library](https://en.wikipedia.org/wiki/Library_(computing)#Shared_libraries) and so it is platform dependent (if my "platform" you mean operating system).

> If no, is it possible to distribute the build result?  This way, user will only need to download and add to path.

The OSQP project already distribute self-contained binaries https://github.com/osqp/osqp-matlab, so I do not think it make a lot of sense to do so. This build system is mainly used to include create osqp matlab bindings that **are explicitly not self-contained** and instead link a shared OSQP library. We use it in https://github.com/robotology/robotology-superbuild, and we also provide conda binaries for it, i.e. : 
~~~
# Create environment
mamba create -n osqpmatlab
mamba activate osqpmatlab
mamba install -n conda-forge -c robotology osqp-matlab
# Launch MATLAB in the same terminal in which the environment is activated and use osqp
~~~~

We also provide a one-line installer in https://github.com/robotology/robotology-superbuild/blob/master/doc/matlab-one-line-install.md, that install a lot of other packages but also `osqp-matlab`.

**Comment by traversaro** [comment]
@yasirroni does this answer your question?

**Comment by yasirroni** [comment]
It is surprisingly easy to embed arbitrary source code to pypi. See my implementation of matpower on pypi: https://pypi.org/project/matpower/

**Comment by yasirroni** [comment]
>>>The OSQP project already distribute self-contained binaries https://github.com/osqp/osqp-matlab,

>>I've not tested it yet. But, I'm using Octave and come here for that. I want to make user able to install OSQP-Octave via pip. So, I need it to be platform independent.

>So my "platform-independent" you actually mean independent from wheater this is used in Octave or MATLAB? 

Thank you. I will only support Octave then. But, what I mean by platform independent is actually an OS independent, on which OS the user use. Worst case scenario, I need to make separate package for each OS.

The main point I came here is to ask a support for **just download** and use. No build started by user. The only thing that user need to do is only add path to Octave search. Is it possible?

**Comment by traversaro** [comment]
> The main point I came here is to ask a support for **just download** and use. No build started by user. The only thing that user need to do is only add path to Octave search. Is it possible?

As explained before, we are not directly interested in Octave support (as we use this in Matlab) nor on a self-contained binary that users can just download and use (as we use conda instead and that is already provided for Matlab by https://github.com/osqp/osqp-matlab). If you want you can submit a PR providing CMake octave support and GitHub actions support to build a self-contained Octave binary and load it for any new release, but it is not something we are going to work on.

**Comment by yasirroni** [comment]
Thank you very much for the replies. I will just leave it as it is for now then. Thanks again.

**Comment by traversaro** [comment]
Ok, feel free to open new issue if it seems fit.
